
#base
FROM ubuntu
MAINTAINER kaustubh deokar <kaustubhd9@gmail.com>

# gets executed during building of the image.
RUN apt-get update

# gets executed when container is built from the image.
CMD ["echo", "Container spun!"]

